FROM ubuntu	

RUN apt-get update
RUN apt-get install -y wget
RUN DEBIAN_FRONTEND=noninteractive apt install -y build-essential pkg-config

# Install CMAKE
RUN apt install -y g++
RUN apt install -y libprotobuf-dev protobuf-compiler
RUN apt install -y cmake
RUN apt install -y libboost-all-dev
RUN apt-get install -y libssl-dev

# Install GAML
RUN apt install -y git
RUN git clone https://github.com/HerveFrezza-Buet/gaml
RUN cd gaml; mkdir -p gaml/build;cd gaml/build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../../..
ENV PKG_CONFIG_PATH=/gaml/gaml/build

# Install cppKafka,
RUN apt-get install -y librdkafka-dev
RUN git clone https://github.com/mfontanini/cppkafka
RUN cd cppkafka;mkdir build;cd build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../..

WORKDIR /generator
ADD tweetoscopeGenerator.hpp /generator
ADD tweet-generator.cpp /generator
ADD params.config 	 /generator
ADD news-data.csv /generator
ADD news-index.csv /generator
RUN g++ -o tweet-generator tweet-generator.cpp -O3 $(pkg-config --cflags --libs gaml) -lpthread -lcppkafka

CMD ./tweet-generator params.config
