FROM python:3.8-slim-buster
WORKDIR /Predictor
ADD predictor.py /Predictor
ADD logger.py   /Predictor

# install libraries
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install kafka-python
RUN pip3 install scikit-learn
RUN pip3 install pickle5
RUN pip3 install termcolor

CMD python3 predictor.py --broker-list localhost:9092 --observation-window 600