FROM python:3.8-slim-buster
WORKDIR /Dashboard
ADD dashboard.py /Dashboard
ADD logger.py /Dashboard

# install libraries
RUN pip3 install kafka-python
RUN pip3 install termcolor

CMD python3 dashboard.py --broker-list localhost:9092
