FROM python:3.8-slim-buster
WORKDIR /Estimator
ADD hawkes_estimator.py /Estimator
ADD labwork_functions.py /Estimator
ADD logger.py   /Estimator

# install libraries
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install kafka-python
RUN pip3 install scikit-learn
RUN pip3 install termcolor

CMD python3 hawkes_estimator.py --broker-list localhost:9092