FROM frolvlad/alpine-python-machinelearning
WORKDIR /Predictor
ADD predictor.py /Predictor
ADD logger.py /Predictor

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 predictor.py --broker-list kafka-service:9092 --observation-window 300
