FROM python:3.8-alpine
cd ..
cd Dashboard
WORKDIR /Dashboard
ADD dashboard.py /Dashboard
ADD logger.py /Dashboard

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 dashboard.py --broker-list kafka-service:9092 --K 10
