FROM python:3.8-alpine
RUN cd ..
cd Monitor
WORKDIR /Monitor
ADD monitor.py /Monitor
ADD logger.py /Monitor

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 monitor.py --broker-list kafka-service:9092
