FROM ubuntu

cd ..
cd Kafka

RUN apt-get update
RUN apt-get install -y wget

# Install java
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk
# Install Kafka

RUN wget https://archive.apache.org/dist/kafka/2.4.1/kafka_2.13-2.4.1.tgz
RUN tar -xzvf kafka_2.13-2.4.1.tgz
RUN rm kafka_2.13-2.4.1.tgz
ENV KAFKA_PATH=/kafka_2.13-2.4.1/

#starting the zookeeper and the  kafka server
ADD kafka.sh /
RUN chmod +x kafka.sh
ADD server.properties /
ADD zookeeper.properties /
CMD ./kafka.sh start --zooconfig zookeeper.properties --serverconfig server.properties
