FROM frolvlad/alpine-python-machinelearning
RUN cd ..
cd Learner
WORKDIR /Learner
ADD learner.py /Learner
ADD logger.py /Learner

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 learner.py --broker-list kafka-service:9092
