FROM python:3.8-alpine
cd ..
cd Collector
WORKDIR /Collector
ADD Collector.py /Collector
ADD Cascade.py /Collector
ADD logger.py /Collector
ADD Processor.py /Collector
ADD Tweet.py /Collector

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 Collector.py --broker-list kafka-service:9092
