FROM python:3.8-alpine
WORKDIR /Logger
ADD logger.py   /Logger

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 logger.py --broker-list localhost:9092