FROM python:3.8-slim-buster
WORKDIR /Logger
ADD logger.py   /Logger

# install libraries
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install kafka-python
RUN pip3 install scikit-learn
RUN pip3 install termcolor

CMD python3 logger.py --broker-list localhost:9092