FROM frolvlad/alpine-python-machinelearning
# already contains scipy, numpy,  sklearn

WORKDIR /Learner
ADD learner.py /Learner
ADD logger.py   /Learner

# install libraries
RUN pip3 install --no-cache-dir kafka-python
RUN pip3 install --no-cache-dir termcolor

CMD python3 learner.py --broker-list localhost:9092
