FROM python:3.8-slim-buster
WORKDIR /Learner
ADD learner.py /Learner
ADD logger.py /Learner

# install libraries
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install kafka-python
RUN pip3 install scikit-learn
RUN pip3 install termcolor

CMD python3 learner.py --broker-list kafka-service:9092
